image: microsoft/dotnet:3.0-sdk

stages:
 - build-core
 - build-models
 - build-extensions
 
before_script:
 - "dotnet restore"
 
build-core:
 stage: build-core
 script:
  - "cd Aiva.Core"
  - "dotnet build"
 tags:
  - dotnet

build-models:
 stage: build-models
 script:
  - "cd Aiva.Models"
  - "dotnet build"
 tags:
  - dotnet
  
build-extensions:
 stage: build-extensions
 script:
  - "cd Aiva.Extensions"
  - "dotnet build"
 tags:
  - dotnet